# Generated by Django 3.0.5 on 2020-04-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0003_weatherdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdetails',
            name='description',
            field=models.CharField(default='clear', max_length=2000),
            preserve_default=False,
        ),
    ]
